import type { Exercise, MuscleGroup } from "./types";

export const MUSCLE_GROUPS: MuscleGroup[] = [
  "Peito",
  "Costas",
  "Ombros",
  "Bíceps",
  "Tríceps",
  "Quadríceps",
  "Glúteos e posterior",
  "Core",
  "Panturrilhas",
];

export const EXERCISE_CATALOG: Exercise[] = [
  {
    id: "push-up",
    name: "Flexão de braço",
    muscleGroup: "Peito",
    secondaryMuscles: ["Tríceps", "Ombros", "Core"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "pushup",
    description:
      "Movimento de empurrar que trabalha o peitoral enquanto o core estabiliza o corpo.",
    steps: [
      "Apoie as mãos um pouco além da largura dos ombros.",
      "Crie uma linha contínua entre cabeça, quadril e tornozelos.",
      "Desça o peito com os cotovelos em diagonal e empurre o chão.",
    ],
    commonMistake: "Deixar o quadril cair ou abrir os cotovelos excessivamente.",
    analyzable: true,
    analysisProfile: "pushup",
    cameraView: "Lateral",
    sortOrder: 1,
    videoId: "Env8gAr_QnE",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=Env8gAr_QnE",
  },
  {
    id: "bench-press",
    name: "Supino reto",
    muscleGroup: "Peito",
    secondaryMuscles: ["Tríceps", "Ombros"],
    equipment: "Barra e banco",
    difficulty: "Intermediário",
    motion: "press",
    description:
      "Exercício composto de empurrar para desenvolver força e massa no peitoral.",
    steps: [
      "Mantenha pés firmes e escápulas apoiadas no banco.",
      "Desça a barra de forma controlada até a linha do peito.",
      "Empurre mantendo punhos alinhados aos antebraços.",
    ],
    commonMistake: "Perder a posição das escápulas ou rebater a barra no peito.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 2,
    videoId: "CjHIKDQ4RQo",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=CjHIKDQ4RQo",
  },
  {
    id: "incline-dumbbell-press",
    name: "Supino inclinado",
    muscleGroup: "Peito",
    secondaryMuscles: ["Ombros", "Tríceps"],
    equipment: "Halteres e banco",
    difficulty: "Intermediário",
    motion: "press",
    description:
      "Variação inclinada com maior participação da porção superior do peitoral.",
    steps: [
      "Ajuste o banco entre 25° e 40°.",
      "Comece com os halteres ao lado do peito.",
      "Empurre para cima sem bater os halteres.",
    ],
    commonMistake:
      "Usar inclinação alta demais e transferir o esforço aos ombros.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 3,
    videoId: "oZVCBM9f8Eo",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=oZVCBM9f8Eo",
  },
  {
    id: "pull-up",
    name: "Barra fixa",
    muscleGroup: "Costas",
    secondaryMuscles: ["Bíceps", "Core"],
    equipment: "Barra fixa",
    difficulty: "Avançado",
    motion: "pullup",
    description:
      "Puxada vertical com o peso corporal para dorsais, braços e estabilizadores.",
    steps: [
      "Segure a barra e organize as escápulas.",
      "Leve o peito em direção à barra sem balançar.",
      "Desça até estender os braços com controle.",
    ],
    commonMistake: "Ganhar impulso com as pernas e encurtar a descida.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal ou lateral",
    sortOrder: 4,
    videoId: "PHdHnZcbsB8",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=PHdHnZcbsB8",
  },
  {
    id: "barbell-row",
    name: "Remada curvada",
    muscleGroup: "Costas",
    secondaryMuscles: ["Bíceps", "Posterior", "Core"],
    equipment: "Barra",
    difficulty: "Intermediário",
    motion: "row",
    description:
      "Puxada horizontal que exige estabilidade do tronco e controle da coluna.",
    steps: [
      "Incline o tronco com quadril para trás e coluna neutra.",
      "Puxe a barra em direção ao abdômen.",
      "Estenda os braços sem perder a posição do tronco.",
    ],
    commonMistake: "Transformar a remada em um balanço do tronco.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 5,
    videoId: "FsK19s8eGFs",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=FsK19s8eGFs",
  },
  {
    id: "lat-pulldown",
    name: "Puxada na frente",
    muscleGroup: "Costas",
    secondaryMuscles: ["Bíceps"],
    equipment: "Polia",
    difficulty: "Iniciante",
    motion: "pullup",
    description:
      "Puxada vertical guiada para aprender a depressão e retração das escápulas.",
    steps: [
      "Sente-se com coxas firmes sob o apoio.",
      "Puxe a barra à parte superior do peito.",
      "Retorne sem elevar os ombros em direção às orelhas.",
    ],
    commonMistake:
      "Inclinar demais o corpo para transformar a puxada em remada.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal ou lateral",
    sortOrder: 6,
    videoId: "JGeRYIZdojU",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=JGeRYIZdojU",
  },
  {
    id: "shoulder-press",
    name: "Desenvolvimento",
    muscleGroup: "Ombros",
    secondaryMuscles: ["Tríceps", "Core"],
    equipment: "Halteres",
    difficulty: "Intermediário",
    motion: "overhead",
    description:
      "Empurrada vertical que desenvolve deltoides e estabilidade acima da cabeça.",
    steps: [
      "Comece com halteres na altura dos ombros.",
      "Mantenha costelas organizadas e abdômen ativo.",
      "Empurre acima da cabeça e retorne com controle.",
    ],
    commonMistake: "Compensar arqueando a lombar e projetando as costelas.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal ou lateral",
    sortOrder: 7,
    videoId: "aI2hGzsAMXs",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=aI2hGzsAMXs",
  },
  {
    id: "lateral-raise",
    name: "Elevação lateral",
    muscleGroup: "Ombros",
    secondaryMuscles: ["Trapézio"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "raise",
    description: "Movimento isolado para a porção lateral dos deltoides.",
    steps: [
      "Mantenha cotovelos levemente flexionados.",
      "Eleve os braços no plano das escápulas.",
      "Pare próximo à linha dos ombros e desça devagar.",
    ],
    commonMistake: "Usar impulso do tronco ou elevar os ombros.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal",
    sortOrder: 8,
    videoId: "D9QydIvJwIQ",
    videoSource: "TrainingPeaks",
    videoUrl: "https://www.youtube.com/watch?v=D9QydIvJwIQ",
  },
  {
    id: "face-pull",
    name: "Face pull",
    muscleGroup: "Ombros",
    secondaryMuscles: ["Costas", "Manguito rotador"],
    equipment: "Polia e corda",
    difficulty: "Iniciante",
    motion: "row",
    description:
      "Puxada alta para deltoide posterior, escápulas e rotadores externos.",
    steps: [
      "Ajuste a corda na altura do rosto.",
      "Puxe separando as pontas da corda.",
      "Termine com mãos ao lado do rosto e cotovelos abertos.",
    ],
    commonMistake:
      "Projetar a cabeça à frente em vez de trazer a corda até o rosto.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 9,
    videoId: "0Po47vvj9g4",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=0Po47vvj9g4",
  },
  {
    id: "barbell-curl",
    name: "Rosca direta",
    muscleGroup: "Bíceps",
    secondaryMuscles: ["Antebraços"],
    equipment: "Barra",
    difficulty: "Iniciante",
    motion: "curl",
    description:
      "Flexão de cotovelos para bíceps com trajetória simples e fácil de acompanhar.",
    steps: [
      "Fique alto com cotovelos ao lado do tronco.",
      "Flexione os cotovelos sem projetar os ombros.",
      "Desça até quase estender os braços, mantendo tensão.",
    ],
    commonMistake:
      "Balançar o tronco e avançar os cotovelos para vencer a carga.",
    analyzable: true,
    analysisProfile: "curl",
    cameraView: "Lateral",
    sortOrder: 10,
    videoId: "N5x5M1x1Gd0",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=N5x5M1x1Gd0",
  },
  {
    id: "hammer-curl",
    name: "Rosca martelo",
    muscleGroup: "Bíceps",
    secondaryMuscles: ["Braquial", "Antebraços"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "curl",
    description: "Flexão com pegada neutra para bíceps, braquial e antebraço.",
    steps: [
      "Segure os halteres com palmas voltadas uma para a outra.",
      "Mantenha cotovelos perto das costelas.",
      "Suba e desça sem girar os punhos.",
    ],
    commonMistake: "Levar o cotovelo para frente e reduzir a tensão no braço.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 11,
    videoId: "B4RznoFvTl4",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=B4RznoFvTl4",
  },
  {
    id: "bench-dip",
    name: "Mergulho no banco",
    muscleGroup: "Tríceps",
    secondaryMuscles: ["Peito", "Ombros"],
    equipment: "Banco",
    difficulty: "Intermediário",
    motion: "dip",
    description: "Extensão de cotovelo com peso corporal e apoio posterior.",
    steps: [
      "Apoie as mãos próximas ao quadril.",
      "Desça mantendo o tronco perto do banco.",
      "Empurre o banco até estender os cotovelos.",
    ],
    commonMistake: "Descer além da mobilidade confortável dos ombros.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 12,
    videoId: "CRP7tS7RIJU",
    videoSource: "OriGym",
    videoUrl: "https://www.youtube.com/watch?v=CRP7tS7RIJU",
  },
  {
    id: "triceps-pushdown",
    name: "Tríceps na polia",
    muscleGroup: "Tríceps",
    secondaryMuscles: ["Antebraços"],
    equipment: "Polia",
    difficulty: "Iniciante",
    motion: "pushdown",
    description:
      "Extensão de cotovelo guiada, simples para controlar carga e amplitude.",
    steps: [
      "Mantenha cotovelos junto ao corpo.",
      "Estenda os braços sem movimentar os ombros.",
      "Retorne até cerca de 90° nos cotovelos.",
    ],
    commonMistake: "Usar o tronco para empurrar a carga para baixo.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 13,
    videoId: "LXkCrxn3caQ",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=LXkCrxn3caQ",
  },
  {
    id: "bodyweight-squat",
    name: "Agachamento livre",
    muscleGroup: "Quadríceps",
    secondaryMuscles: ["Glúteos", "Core", "Posterior"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "squat",
    description:
      "Padrão fundamental de agachar com participação de quadris, joelhos e tornozelos.",
    steps: [
      "Posicione os pés em uma base confortável.",
      "Desça flexionando quadris e joelhos com pés firmes.",
      "Suba acompanhando a direção dos pés com os joelhos.",
    ],
    commonMistake:
      "Perder o apoio dos pés ou deixar os joelhos colapsarem para dentro.",
    analyzable: true,
    analysisProfile: "squat",
    cameraView: "Frontal ou lateral",
    sortOrder: 14,
    videoId: "l83R5PblSMA",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=l83R5PblSMA",
  },
  {
    id: "reverse-lunge",
    name: "Afundo caminhando",
    muscleGroup: "Quadríceps",
    secondaryMuscles: ["Glúteos", "Posterior", "Core"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "lunge",
    description:
      "Afundo em deslocamento contínuo, alternando as pernas a cada passada.",
    steps: [
      "Dê um passo à frente mantendo os pés alinhados aos quadris.",
      "Desça os dois joelhos com o tronco firme e o core ativo.",
      "Empurre o chão e leve a perna de trás diretamente à próxima passada.",
    ],
    commonMistake:
      "Cruzar os pés, perder o equilíbrio ou inclinar demais o tronco.",
    analyzable: true,
    analysisProfile: "lunge",
    cameraView: "Lateral",
    sortOrder: 15,
    videoId: "mAgbXQdd4LM",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=mAgbXQdd4LM",
  },
  {
    id: "leg-press",
    name: "Leg press",
    muscleGroup: "Quadríceps",
    secondaryMuscles: ["Glúteos", "Posterior"],
    equipment: "Máquina",
    difficulty: "Iniciante",
    motion: "squat",
    description:
      "Empurrada de pernas guiada para acumular volume com estabilidade externa.",
    steps: [
      "Apoie toda a planta dos pés na plataforma.",
      "Desça até manter quadril e lombar apoiados.",
      "Empurre sem travar agressivamente os joelhos.",
    ],
    commonMistake: "Descer tanto que o quadril se afasta do encosto.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 16,
    videoId: "q4W4_VJbKW0",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=q4W4_VJbKW0",
  },
  {
    id: "romanian-deadlift",
    name: "Levantamento romeno",
    muscleGroup: "Glúteos e posterior",
    secondaryMuscles: ["Costas", "Core"],
    equipment: "Barra",
    difficulty: "Intermediário",
    motion: "hinge",
    description:
      "Dobradiça de quadril para posteriores e glúteos com coluna estável.",
    steps: [
      "Destrave os joelhos e leve o quadril para trás.",
      "Mantenha a barra próxima às pernas.",
      "Suba estendendo o quadril sem inclinar-se para trás.",
    ],
    commonMistake:
      "Transformar o movimento em agachamento ou arredondar a coluna.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 17,
    videoId: "zU-f6DMCdAI",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=zU-f6DMCdAI",
  },
  {
    id: "hip-thrust",
    name: "Hip thrust",
    muscleGroup: "Glúteos e posterior",
    secondaryMuscles: ["Posterior", "Core"],
    equipment: "Banco e barra",
    difficulty: "Intermediário",
    motion: "bridge",
    description: "Extensão de quadril com grande participação dos glúteos.",
    steps: [
      "Apoie as escápulas no banco e mantenha pés firmes.",
      "Eleve o quadril até alinhar joelhos, quadril e ombros.",
      "Desça sem perder o controle da pelve.",
    ],
    commonMistake: "Finalizar hiperestendendo a lombar em vez do quadril.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 18,
    videoId: "7XuNzi5rcj4",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=7XuNzi5rcj4",
  },
  {
    id: "glute-bridge",
    name: "Ponte de glúteos",
    muscleGroup: "Glúteos e posterior",
    secondaryMuscles: ["Core"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "bridge",
    description: "Introdução à extensão de quadril realizada no solo.",
    steps: [
      "Deite com joelhos flexionados e pés apoiados.",
      "Contraia o abdômen e eleve o quadril.",
      "Pare quando o tronco se alinhar às coxas e desça.",
    ],
    commonMistake: "Subir empurrando a lombar em vez de contrair os glúteos.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 19,
    videoId: "tqp5XQPpTxY",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=tqp5XQPpTxY",
  },
  {
    id: "plank",
    name: "Prancha",
    muscleGroup: "Core",
    secondaryMuscles: ["Ombros", "Glúteos"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "plank",
    description: "Estabilização isométrica do tronco contra a extensão da coluna.",
    steps: [
      "Apoie antebraços abaixo dos ombros.",
      "Alinhe cabeça, quadril e tornozelos.",
      "Respire mantendo abdômen e glúteos ativos.",
    ],
    commonMistake: "Deixar o quadril cair ou prender a respiração.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 20,
    videoId: "q4rDeHYMcIg",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=q4rDeHYMcIg",
  },
  {
    id: "dead-bug",
    name: "Dead bug",
    muscleGroup: "Core",
    secondaryMuscles: ["Flexores do quadril"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "core",
    description:
      "Controle do tronco enquanto braços e pernas se movem de forma alternada.",
    steps: [
      "Deite com braços altos e joelhos a 90°.",
      "Estenda braço e perna opostos sem perder a lombar.",
      "Retorne e alterne os lados lentamente.",
    ],
    commonMistake:
      "Acelerar o movimento e deixar a lombar se afastar do chão.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 21,
    videoId: "9RK9UUgKIQE",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=9RK9UUgKIQE",
  },
  {
    id: "crunch",
    name: "Abdominal curto",
    muscleGroup: "Core",
    secondaryMuscles: ["Flexores do quadril"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "crunch",
    description: "Flexão controlada do tronco com amplitude curta.",
    steps: [
      "Apoie os pés e mantenha o pescoço relaxado.",
      "Aproxime as costelas da pelve sem puxar a cabeça.",
      "Desça lentamente até apoiar as escápulas.",
    ],
    commonMistake: "Puxar o pescoço com as mãos para ganhar amplitude.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 22,
    videoId: "NnVhqMQRvmM",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=NnVhqMQRvmM",
  },
  {
    id: "standing-calf-raise",
    name: "Elevação de panturrilha",
    muscleGroup: "Panturrilhas",
    secondaryMuscles: ["Pés e tornozelos"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "calf",
    description:
      "Flexão plantar para fortalecer panturrilhas e controle dos tornozelos.",
    steps: [
      "Mantenha pés paralelos e use apoio leve se necessário.",
      "Eleve os calcanhares o máximo que controla.",
      "Desça devagar até alongar a panturrilha.",
    ],
    commonMistake:
      "Quicar rapidamente e deixar os tornozelos tombarem para fora.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal ou lateral",
    sortOrder: 23,
    videoId: "Zep-wKHWkNM",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=Zep-wKHWkNM",
  },
];

export const PROFILE_TO_EXERCISE_ID = {
  squat: "bodyweight-squat",
  pushup: "push-up",
  curl: "barbell-curl",
  lunge: "reverse-lunge",
} as const;

export function getExerciseById(
  id: string,
  catalog: Exercise[] = EXERCISE_CATALOG,
): Exercise | undefined {
  return catalog.find((exercise) => exercise.id === id);
}

export function youtubeThumbnail(videoId: string): string {
  return `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;
}
