import type {
  EquipmentAlternative,
  EquipmentTag,
  Exercise,
  LocationTag,
} from "@/lib/types";

export const ALL_LOCATIONS: LocationTag[] = [
  "casa",
  "academia",
  "ar_livre",
  "outro",
];

export const HOME_LOCATIONS: LocationTag[] = ["casa", "academia", "outro"];

export const GYM_ONLY: LocationTag[] = ["academia"];

interface GearMeta {
  equipmentRequired: EquipmentTag[];
  locationCompatible: LocationTag[];
  equipmentAlternatives?: EquipmentAlternative[];
}

const bodyweight = (locations: LocationTag[] = ALL_LOCATIONS): GearMeta => ({
  equipmentRequired: ["nenhum"],
  locationCompatible: locations,
});

/** Metadados dos 23 exercícios originais — o catálogo em si não é reescrito. */
export const CATALOG_GEAR: Record<string, GearMeta> = {
  "push-up": bodyweight(),
  "bench-press": {
    equipmentRequired: ["barra", "banco", "anilhas"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "barra", substituteExerciseId: "incline-dumbbell-press" },
      { missing: "banco", substituteExerciseId: "floor-dumbbell-press" },
      { missing: "anilhas", substituteExerciseId: "push-up" },
    ],
  },
  "incline-dumbbell-press": {
    equipmentRequired: ["halteres", "banco"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "banco", substituteExerciseId: "floor-dumbbell-press" },
      { missing: "halteres", substituteExerciseId: "push-up" },
    ],
  },
  "pull-up": {
    equipmentRequired: ["barra_fixa"],
    locationCompatible: ["casa", "academia", "ar_livre"],
    equipmentAlternatives: [
      { missing: "barra_fixa", substituteExerciseId: "lat-pulldown" },
      { missing: "barra_fixa", substituteExerciseId: "inverted-row" },
      { missing: "barra_fixa", substituteExerciseId: "superman" },
    ],
  },
  "barbell-row": {
    equipmentRequired: ["barra", "anilhas"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "barra", substituteExerciseId: "dumbbell-row" },
      { missing: "anilhas", substituteExerciseId: "inverted-row" },
    ],
  },
  "lat-pulldown": {
    equipmentRequired: ["cabos", "maquinas"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "cabos", substituteExerciseId: "pull-up" },
      { missing: "maquinas", substituteExerciseId: "inverted-row" },
    ],
  },
  "shoulder-press": {
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "pike-push-up" },
    ],
  },
  "lateral-raise": {
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "pike-push-up" },
    ],
  },
  "face-pull": {
    equipmentRequired: ["cabos"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "cabos", substituteExerciseId: "band-pull-apart" },
      { missing: "cabos", substituteExerciseId: "reverse-fly" },
      { missing: "cabos", substituteExerciseId: "superman" },
    ],
  },
  "barbell-curl": {
    equipmentRequired: ["barra", "anilhas"],
    locationCompatible: ["casa", "academia"],
    equipmentAlternatives: [
      { missing: "barra", substituteExerciseId: "hammer-curl" },
      { missing: "anilhas", substituteExerciseId: "towel-curl" },
    ],
  },
  "hammer-curl": {
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "towel-curl" },
    ],
  },
  "bench-dip": {
    equipmentRequired: ["banco"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "banco", substituteExerciseId: "diamond-push-up" },
    ],
  },
  "triceps-pushdown": {
    equipmentRequired: ["cabos"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "cabos", substituteExerciseId: "diamond-push-up" },
    ],
  },
  "bodyweight-squat": bodyweight(),
  "reverse-lunge": bodyweight(),
  "leg-press": {
    equipmentRequired: ["leg_press", "maquinas"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "leg_press", substituteExerciseId: "bodyweight-squat" },
      { missing: "maquinas", substituteExerciseId: "goblet-squat" },
    ],
  },
  "romanian-deadlift": {
    equipmentRequired: ["barra", "anilhas"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "barra", substituteExerciseId: "dumbbell-rdl" },
      { missing: "barra", substituteExerciseId: "glute-bridge" },
    ],
  },
  "hip-thrust": {
    equipmentRequired: ["banco", "barra"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "banco", substituteExerciseId: "glute-bridge" },
      { missing: "barra", substituteExerciseId: "single-leg-glute-bridge" },
    ],
  },
  "glute-bridge": bodyweight(HOME_LOCATIONS),
  plank: bodyweight(),
  "dead-bug": bodyweight(HOME_LOCATIONS),
  crunch: bodyweight(),
  "standing-calf-raise": bodyweight(),
};

export const EXTRA_EXERCISES: Exercise[] = [
  {
    id: "floor-dumbbell-press",
    name: "Supino no chão",
    muscleGroup: "Peito",
    secondaryMuscles: ["Tríceps", "Ombros"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "press",
    description:
      "Empurrada de peito no solo, útil quando não há banco e ainda há halteres.",
    steps: [
      "Deite no chão com os joelhos flexionados e os halteres ao lado do peito.",
      "Empurre até estender os cotovelos sem bater os halteres.",
      "Desça até os braços tocarem o chão com controle.",
    ],
    commonMistake: "Abrir demais os cotovelos ou perder o contato das escápulas.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 24,
    videoId: "uUGDRwge4F8",
    videoSource: "Jeff Nippard",
    videoUrl: "https://www.youtube.com/watch?v=uUGDRwge4F8",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "push-up" },
    ],
  },
  {
    id: "superman",
    name: "Superman",
    muscleGroup: "Costas",
    secondaryMuscles: ["Glúteos", "Abdômen"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "extension",
    description:
      "Extensão de tronco no solo para a cadeia posterior quando não há barra nem polia.",
    steps: [
      "Deite de barriga para baixo com braços à frente.",
      "Eleve braços e pernas juntos, sem jogar o pescoço para trás.",
      "Segure um instante e desça com controle.",
    ],
    commonMistake: "Hiperextender o pescoço ou usar impulso para subir.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 25,
    videoId: "cc6UVRS7PW4",
    videoSource: "Get Healthy U",
    videoUrl: "https://www.youtube.com/watch?v=cc6UVRS7PW4",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
  },
  {
    id: "inverted-row",
    name: "Remada invertida",
    muscleGroup: "Costas",
    secondaryMuscles: ["Bíceps", "Abdômen"],
    equipment: "Peso corporal",
    difficulty: "Intermediário",
    motion: "row",
    description:
      "Puxada horizontal com o próprio corpo, usando mesa firme ou barra baixa.",
    steps: [
      "Segure uma barra baixa ou a borda de uma mesa estável.",
      "Mantenha o corpo em linha e puxe o peito em direção ao apoio.",
      "Desça até estender os braços sem perder a linha do tronco.",
    ],
    commonMistake: "Deixar o quadril cair ou encurtar a amplitude.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 26,
    videoId: "hXTc1mDnZCw",
    videoSource: "BarBend",
    videoUrl: "https://www.youtube.com/watch?v=hXTc1mDnZCw",
    equipmentRequired: ["nenhum"],
    locationCompatible: HOME_LOCATIONS,
  },
  {
    id: "dumbbell-row",
    name: "Remada com halter",
    muscleGroup: "Costas",
    secondaryMuscles: ["Bíceps", "Abdômen"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "row",
    description:
      "Puxada unilateral com halter, alternativa à remada curvada com barra.",
    steps: [
      "Apoie uma mão e o joelho no banco ou numa superfície estável.",
      "Puxe o halter em direção ao quadril com a escápula organizada.",
      "Desça com controle sem girar o tronco.",
    ],
    commonMistake: "Usar o tronco para balançar a carga.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 27,
    videoId: "pYcpY20QaE8",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=pYcpY20QaE8",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "inverted-row" },
    ],
  },
  {
    id: "pike-push-up",
    name: "Flexão pike",
    muscleGroup: "Ombros",
    secondaryMuscles: ["Tríceps", "Abdômen"],
    equipment: "Peso corporal",
    difficulty: "Intermediário",
    motion: "overhead",
    description:
      "Empurrada vertical com o peso do corpo, quando não há halteres para o desenvolvimento.",
    steps: [
      "Forme um V invertido com o quadril alto e as mãos no chão.",
      "Desça a cabeça em direção ao chão flexionando os cotovelos.",
      "Empurre de volta sem arquear a lombar.",
    ],
    commonMistake: "Deixar o peso nos pés em vez de nas mãos.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 28,
    videoId: "RmKUhj62_9c",
    videoSource: "Calisthenic Movement",
    videoUrl: "https://www.youtube.com/watch?v=RmKUhj62_9c",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
  },
  {
    id: "towel-curl",
    name: "Rosca isométrica",
    muscleGroup: "Bíceps",
    secondaryMuscles: ["Antebraços"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "curl",
    description:
      "Flexão de cotovelo contra a própria resistência, para treinar bíceps sem carga.",
    steps: [
      "Encaixe as palmas sob uma toalha, mesa ou contra a outra mão.",
      "Tente flexionar os cotovelos sem deixar o tronco balançar.",
      "Mantenha a tensão alguns segundos e relaxe com controle.",
    ],
    commonMistake: "Prender a respiração ou usar os ombros para compensar.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 29,
    videoId: "crIlyqOfHmY",
    videoSource: "Littauer Strength Training",
    videoUrl: "https://www.youtube.com/watch?v=crIlyqOfHmY",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
  },
  {
    id: "diamond-push-up",
    name: "Flexão diamante",
    muscleGroup: "Tríceps",
    secondaryMuscles: ["Peito", "Ombros"],
    equipment: "Peso corporal",
    difficulty: "Intermediário",
    motion: "pushup",
    description:
      "Flexão com as mãos próximas para deslocar o esforço ao tríceps, sem banco nem polia.",
    steps: [
      "Una polegares e indicadores sob o peito.",
      "Desça com o corpo em linha e os cotovelos junto ao tronco.",
      "Empurre o chão até estender os braços.",
    ],
    commonMistake: "Abrir os cotovelos ou deixar o quadril cair.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 30,
    videoId: "J0DnG1_S92I",
    videoSource: "Calisthenic Movement",
    videoUrl: "https://www.youtube.com/watch?v=J0DnG1_S92I",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
  },
  {
    id: "goblet-squat",
    name: "Agachamento goblet",
    muscleGroup: "Quadríceps",
    secondaryMuscles: ["Glúteos", "Abdômen"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "squat",
    description:
      "Agachamento com carga na frente do corpo, para casa com um único halter.",
    steps: [
      "Segure o halter junto ao peito.",
      "Desça com o tronco alto e os cotovelos entre os joelhos.",
      "Suba empurrando o chão sem perder o apoio dos pés.",
    ],
    commonMistake: "Deixar o tronco cair para frente ou os calcanhares levantarem.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal ou lateral",
    sortOrder: 31,
    videoId: "MeIiIdhvXT4",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=MeIiIdhvXT4",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "bodyweight-squat" },
    ],
  },
  {
    id: "single-leg-glute-bridge",
    name: "Ponte de glúteos unilateral",
    muscleGroup: "Glúteos e posterior",
    secondaryMuscles: ["Abdômen", "Posterior"],
    equipment: "Peso corporal",
    difficulty: "Intermediário",
    motion: "bridge",
    description:
      "Variação unilateral da ponte para progredir sem carga externa.",
    steps: [
      "Deite com um pé apoiado e a outra perna estendida.",
      "Eleve o quadril contraia o glúteo da perna de apoio.",
      "Desça sem deixar a pelve girar.",
    ],
    commonMistake: "Empurrar a lombar em vez de estender o quadril.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 32,
    videoId: "_K_di6h2-Wg",
    videoSource: "Well+Good",
    videoUrl: "https://www.youtube.com/watch?v=_K_di6h2-Wg",
    equipmentRequired: ["nenhum"],
    locationCompatible: HOME_LOCATIONS,
  },
  {
    id: "dumbbell-tricep-extension",
    name: "Tríceps testa com halter",
    muscleGroup: "Tríceps",
    secondaryMuscles: ["Antebraços"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "extension",
    description:
      "Extensão de cotovelo com halter, alternativa à polia quando só há pesos livres.",
    steps: [
      "Deite ou sente com o halter acima da cabeça.",
      "Flexione os cotovelos sem abrir os braços.",
      "Estenda até quase travar, mantendo os cotovelos estáveis.",
    ],
    commonMistake: "Deixar os cotovelos abrirem e perder a tensão no tríceps.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 33,
    videoId: "ir5PsbniVSc",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=ir5PsbniVSc",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "diamond-push-up" },
    ],
  },
  {
    id: "incline-push-up",
    name: "Flexão inclinada",
    muscleGroup: "Peito",
    secondaryMuscles: ["Tríceps", "Ombros"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "pushup",
    description:
      "Flexão com as mãos elevadas, para reduzir a carga quando o movimento no chão ainda é difícil.",
    steps: [
      "Apoie as mãos numa superfície estável na altura do quadril ou um pouco abaixo.",
      "Desça o peito em direção ao apoio com o corpo em linha.",
      "Empurre até estender os braços sem perder a organização das escápulas.",
    ],
    commonMistake: "Deixar o quadril cair ou encurtar a amplitude no fundo.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 34,
    videoId: "cfns5VDVVvk",
    videoSource: "Train With Adby",
    videoUrl: "https://www.youtube.com/watch?v=cfns5VDVVvk",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
    equipmentAlternatives: [
      { missing: "nenhum", substituteExerciseId: "knee-push-up" },
    ],
  },
  {
    id: "knee-push-up",
    name: "Flexão com joelhos apoiados",
    muscleGroup: "Peito",
    secondaryMuscles: ["Tríceps", "Ombros"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "pushup",
    description:
      "Variação da flexão com os joelhos no chão, para treinar o padrão de empurrar sem equipamento.",
    steps: [
      "Apoie joelhos e mãos no chão, com o tronco em linha até os joelhos.",
      "Desça o peito em direção ao chão flexionando os cotovelos.",
      "Empurre de volta sem perder a linha dos ombros até o quadril.",
    ],
    commonMistake: "Quebrar a linha do tronco ou abrir demais os cotovelos.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 35,
    videoId: "lFR1GWy1Dcs",
    videoSource: "Dr. Carl Baird",
    videoUrl: "https://www.youtube.com/watch?v=lFR1GWy1Dcs",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
    equipmentAlternatives: [
      { missing: "nenhum", substituteExerciseId: "incline-push-up" },
    ],
  },
  {
    id: "dumbbell-fly",
    name: "Crucifixo com halter",
    muscleGroup: "Peito",
    secondaryMuscles: ["Ombros"],
    equipment: "Halteres e banco",
    difficulty: "Iniciante",
    motion: "fly",
    description:
      "Abertura de peito no banco, para alongar o peitoral além do padrão de empurrar.",
    steps: [
      "Deite no banco com os halteres acima do peito e os cotovelos levemente flexionados.",
      "Abra os braços em arco até sentir o peitoral alongar, sem perder o arco das costelas.",
      "Feche os halteres de volta ao centro sem bater um no outro.",
    ],
    commonMistake: "Estender demais os cotovelos ou descer além do que o ombro controla.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 36,
    videoId: "eozdVDA78K0",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=eozdVDA78K0",
    equipmentRequired: ["halteres", "banco"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "banco", substituteExerciseId: "floor-dumbbell-press" },
      { missing: "halteres", substituteExerciseId: "push-up" },
    ],
  },
  {
    id: "decline-push-up",
    name: "Flexão declinada",
    muscleGroup: "Peito",
    secondaryMuscles: ["Tríceps", "Ombros", "Abdômen"],
    equipment: "Peso corporal",
    difficulty: "Intermediário",
    motion: "pushup",
    description:
      "Flexão com os pés elevados, para aumentar a carga no peitoral sem equipamento.",
    steps: [
      "Apoie os pés numa superfície estável e as mãos no chão, um pouco além da largura dos ombros.",
      "Desça o peito com o corpo em linha, como numa prancha inclinada.",
      "Empurre até estender os braços sem deixar o quadril cair.",
    ],
    commonMistake: "Abrir demais os cotovelos ou perder a linha da prancha.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 37,
    videoId: "SKPab2YC8BE",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=SKPab2YC8BE",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
    equipmentAlternatives: [
      { missing: "nenhum", substituteExerciseId: "push-up" },
    ],
  },
  {
    id: "chin-up",
    name: "Barra supinada",
    muscleGroup: "Costas",
    secondaryMuscles: ["Bíceps", "Abdômen"],
    equipment: "Barra fixa",
    difficulty: "Intermediário",
    motion: "pull",
    description:
      "Puxada na barra com palmas voltadas para você, com mais participação do bíceps que a barra pronada.",
    steps: [
      "Segure a barra com as palmas para você, um pouco mais estreitas que os ombros.",
      "Puxe o peito em direção à barra sem balançar as pernas.",
      "Desça até quase estender os cotovelos, sem soltar as escápulas.",
    ],
    commonMistake: "Usar impulso das pernas ou encolher os ombros até as orelhas.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 38,
    videoId: "brhRXlOhsAM",
    videoSource: "Buff Dudes",
    videoUrl: "https://www.youtube.com/watch?v=brhRXlOhsAM",
    equipmentRequired: ["barra_fixa"],
    locationCompatible: ["casa", "academia", "ar_livre"],
    equipmentAlternatives: [
      { missing: "barra_fixa", substituteExerciseId: "lat-pulldown" },
      { missing: "barra_fixa", substituteExerciseId: "inverted-row" },
    ],
  },
  {
    id: "seated-cable-row",
    name: "Remada sentada no cabo",
    muscleGroup: "Costas",
    secondaryMuscles: ["Bíceps", "Abdômen"],
    equipment: "Cabos",
    difficulty: "Iniciante",
    motion: "row",
    description:
      "Puxada horizontal na polia sentada, para costas médias com amplitude controlada.",
    steps: [
      "Sente com os pés apoiados, joelhos levemente flexionados e tronco alto.",
      "Puxe o cabo em direção ao umbigo, cotovelos junto ao tronco.",
      "Volte até alongar as costas sem arredondar a lombar.",
    ],
    commonMistake: "Balançar o tronco para trás para puxar mais carga.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 39,
    videoId: "GZbfZ033f74",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=GZbfZ033f74",
    equipmentRequired: ["cabos"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "cabos", substituteExerciseId: "dumbbell-row" },
      { missing: "cabos", substituteExerciseId: "inverted-row" },
    ],
  },
  {
    id: "reverse-fly",
    name: "Crucifixo invertido",
    muscleGroup: "Ombros",
    secondaryMuscles: ["Costas"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "fly",
    description:
      "Abertura inclinada para o deltoide posterior e a parte alta das costas.",
    steps: [
      "Incline o tronco com a coluna neutra e os halteres pendurados à frente.",
      "Abra os braços para o lado, com cotovelos levemente flexionados.",
      "Aperte as escápulas no topo e desça com controle.",
    ],
    commonMistake: "Usar o impulso do tronco ou elevar os ombros até as orelhas.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 40,
    videoId: "ttvfGg9d76c",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=ttvfGg9d76c",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "band-pull-apart" },
      { missing: "halteres", substituteExerciseId: "superman" },
    ],
  },
  {
    id: "front-raise",
    name: "Elevação frontal",
    muscleGroup: "Ombros",
    secondaryMuscles: ["Peito"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "raise",
    description:
      "Elevação à frente para o deltoide anterior, complementar ao desenvolvimento e à elevação lateral.",
    steps: [
      "Em pé, segure os halteres na frente das coxas com o tronco estável.",
      "Eleve um ou os dois braços até a linha dos ombros, sem balançar o corpo.",
      "Desça com controle até a posição inicial.",
    ],
    commonMistake: "Usar o impulso do quadril ou subir os braços acima da cabeça.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 41,
    videoId: "-t7fuZ0KhDA",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=-t7fuZ0KhDA",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "pike-push-up" },
    ],
  },
  {
    id: "shrug",
    name: "Encolhimento com halter",
    muscleGroup: "Ombros",
    secondaryMuscles: ["Costas"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "shrug",
    description:
      "Elevação dos ombros para o trapézio superior, com carga nas mãos ao lado do corpo.",
    steps: [
      "Em pé, segure os halteres ao lado das coxas com os braços longos.",
      "Encolha os ombros em direção às orelhas sem dobrar os cotovelos.",
      "Segure um instante no topo e desça com controle.",
    ],
    commonMistake: "Rolar os ombros em círculo ou usar o pescoço para puxar.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal ou lateral",
    sortOrder: 42,
    videoId: "cJRVVxmytaM",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=cJRVVxmytaM",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "superman" },
    ],
  },
  {
    id: "arnold-press",
    name: "Desenvolvimento Arnold",
    muscleGroup: "Ombros",
    secondaryMuscles: ["Tríceps"],
    equipment: "Halteres",
    difficulty: "Intermediário",
    motion: "overhead",
    description:
      "Desenvolvimento com rotação dos halteres, para cobrir as três porções do deltoide.",
    steps: [
      "Comece com os halteres à frente dos ombros, palmas voltadas para você.",
      "Gire as palmas para frente enquanto empurra acima da cabeça.",
      "Desça o mesmo caminho, voltando as palmas para o peito.",
    ],
    commonMistake: "Arquear a lombar para empurrar a carga ou perder a rotação no meio do caminho.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal ou lateral",
    sortOrder: 43,
    videoId: "6Z15_WdXmVw",
    videoSource: "Buff Dudes",
    videoUrl: "https://www.youtube.com/watch?v=6Z15_WdXmVw",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "pike-push-up" },
    ],
  },
  {
    id: "band-pull-apart",
    name: "Abertura com elástico",
    muscleGroup: "Ombros",
    secondaryMuscles: ["Costas"],
    equipment: "Elástico",
    difficulty: "Iniciante",
    motion: "pull",
    description:
      "Abertura horizontal com elástico para deltoide posterior e postura, fácil de fazer em qualquer lugar.",
    steps: [
      "Segure o elástico à frente do peito, braços longos e ombros baixos.",
      "Abra até o elástico tocar o peito, apertando as escápulas.",
      "Volte com controle sem deixar os ombros subirem.",
    ],
    commonMistake: "Dobrar os cotovelos demais e transformar o movimento em tríceps.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal",
    sortOrder: 44,
    videoId: "gGJiCYopsc0",
    videoSource: "Kennedy Health and Fitness",
    videoUrl: "https://www.youtube.com/watch?v=gGJiCYopsc0",
    equipmentRequired: ["elastico"],
    locationCompatible: ALL_LOCATIONS,
    equipmentAlternatives: [
      { missing: "elastico", substituteExerciseId: "reverse-fly" },
      { missing: "elastico", substituteExerciseId: "superman" },
    ],
  },
  {
    id: "concentration-curl",
    name: "Rosca concentrada",
    muscleGroup: "Bíceps",
    secondaryMuscles: ["Antebraços"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "curl",
    description:
      "Rosca unilateral sentada, para isolar o bíceps sem balanço do tronco.",
    steps: [
      "Sente com o cotovelo apoiado na parte interna da coxa.",
      "Flexione o cotovelo até o halter chegar perto do ombro.",
      "Desça até quase estender o braço, sem perder o apoio do cotovelo.",
    ],
    commonMistake: "Inclinar o tronco para trás para completar a repetição.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 45,
    videoId: "0AUGkch3tzc",
    videoSource: "Howcast",
    videoUrl: "https://www.youtube.com/watch?v=0AUGkch3tzc",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "towel-curl" },
    ],
  },
  {
    id: "tricep-kickback",
    name: "Kickback de tríceps",
    muscleGroup: "Tríceps",
    secondaryMuscles: ["Costas"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "extension",
    description:
      "Extensão de cotovelo inclinada com halter, para tríceps quando não há polia.",
    steps: [
      "Incline o tronco e deixe o braço de trabalho paralelo ao chão.",
      "Estenda o cotovelo para trás sem mover o ombro.",
      "Volte até cerca de 90° e repita com controle.",
    ],
    commonMistake: "Balançar o braço inteiro em vez de só estender o cotovelo.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 46,
    videoId: "6SS6K3lAwZ8",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=6SS6K3lAwZ8",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "diamond-push-up" },
    ],
  },
  {
    id: "overhead-tricep-extension",
    name: "Tríceps francês em pé",
    muscleGroup: "Tríceps",
    secondaryMuscles: ["Abdômen"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "extension",
    description:
      "Extensão acima da cabeça com halter, para a cabeça longa do tríceps.",
    steps: [
      "Segure o halter acima da cabeça com os cotovelos apontando para frente.",
      "Flexione os cotovelos atrás da cabeça sem abrir os braços.",
      "Estenda de volta até quase travar, mantendo o tronco firme.",
    ],
    commonMistake: "Deixar os cotovelos abrirem ou arquear a lombar.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 47,
    videoId: "-Vyt2QdsR7E",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=-Vyt2QdsR7E",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "diamond-push-up" },
    ],
  },
  {
    id: "bulgarian-split-squat",
    name: "Afundo búlgaro",
    muscleGroup: "Quadríceps",
    secondaryMuscles: ["Glúteos", "Abdômen"],
    equipment: "Halteres",
    difficulty: "Intermediário",
    motion: "lunge",
    description:
      "Afundo com o pé de trás elevado, para pernas e glúteos com pouca carga e muito controle.",
    steps: [
      "Apoie o peito do pé de trás num banco ou cadeira estável.",
      "Desça o joelho de trás em direção ao chão, com o tronco alto.",
      "Suba empurrando o chão com o pé da frente, sem perder o equilíbrio.",
    ],
    commonMistake: "Avançar demais o joelho da frente ou deixar o tronco cair.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 48,
    videoId: "AaCqSV2vpn4",
    videoSource: "Dr. Donald Ozello",
    videoUrl: "https://www.youtube.com/watch?v=AaCqSV2vpn4",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "reverse-lunge" },
    ],
  },
  {
    id: "wall-sit",
    name: "Isometria na parede",
    muscleGroup: "Quadríceps",
    secondaryMuscles: ["Glúteos", "Abdômen"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "squat",
    description:
      "Agachamento estático contra a parede, para resistência de quadríceps sem equipamento.",
    steps: [
      "Encoste as costas na parede e afaste os pés cerca de um passo.",
      "Desça até os joelhos ficarem próximos de 90°, com os calcanhares no chão.",
      "Segure o tempo combinado sem apoiar as mãos nas coxas.",
    ],
    commonMistake: "Deixar os joelhos passarem dos pés ou descolar a lombar da parede.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 49,
    videoId: "6Li55TURhVg",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=6Li55TURhVg",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
  },
  {
    id: "step-up",
    name: "Step-up",
    muscleGroup: "Quadríceps",
    secondaryMuscles: ["Glúteos", "Abdômen"],
    equipment: "Halteres",
    difficulty: "Iniciante",
    motion: "lunge",
    description:
      "Subida num banco ou caixote, para pernas unilaterais com padrão do dia a dia.",
    steps: [
      "Coloque o pé inteiro no banco, com os halteres ao lado do corpo.",
      "Suba empurrando o calcanhar da perna de cima, sem impulsionar com a de trás.",
      "Desça com controle pelo mesmo pé e alterne os lados.",
    ],
    commonMistake: "Usar o pé de trás para empurrar ou pisar só com a ponta do pé.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 50,
    videoId: "DxUNi119Qzs",
    videoSource: "PureGym",
    videoUrl: "https://www.youtube.com/watch?v=DxUNi119Qzs",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "reverse-lunge" },
    ],
  },
  {
    id: "dumbbell-rdl",
    name: "Levantamento romeno com halter",
    muscleGroup: "Glúteos e posterior",
    secondaryMuscles: ["Abdômen", "Costas"],
    equipment: "Halteres",
    difficulty: "Intermediário",
    motion: "hinge",
    description:
      "Dobradiça de quadril com halteres, alternativa ao romeno com barra para casa ou academia.",
    steps: [
      "Segure os halteres na frente das coxas, joelhos levemente flexionados.",
      "Empurre o quadril para trás descendo os pesos junto às pernas.",
      "Suba estendendo o quadril e contraindo os glúteos, sem arredondar a lombar.",
    ],
    commonMistake: "Dobrar demais os joelhos ou deixar a coluna ceder no fundo.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 51,
    videoId: "FQKfr1YDhEk",
    videoSource: "Scott Herman Fitness",
    videoUrl: "https://www.youtube.com/watch?v=FQKfr1YDhEk",
    equipmentRequired: ["halteres"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "halteres", substituteExerciseId: "glute-bridge" },
    ],
  },
  {
    id: "donkey-kick",
    name: "Coice de glúteo",
    muscleGroup: "Glúteos e posterior",
    secondaryMuscles: ["Abdômen"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "kick",
    description:
      "Extensão de quadril a quatro apoios para isolar o glúteo sem carga externa.",
    steps: [
      "Fique de quatro, pulsos sob os ombros e joelhos sob o quadril.",
      "Mantenha o joelho a 90° e empurre o calcanhar em direção ao teto.",
      "Desça sem encostar o joelho no chão e complete o lado antes de trocar.",
    ],
    commonMistake: "Arquear a lombar para levantar a perna mais alto.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 52,
    videoId: "QreOl2tgC-8",
    videoSource: "Well+Good",
    videoUrl: "https://www.youtube.com/watch?v=QreOl2tgC-8",
    equipmentRequired: ["nenhum"],
    locationCompatible: HOME_LOCATIONS,
  },
  {
    id: "kettlebell-swing",
    name: "Swing com kettlebell",
    muscleGroup: "Glúteos e posterior",
    secondaryMuscles: ["Abdômen", "Ombros"],
    equipment: "Kettlebell",
    difficulty: "Intermediário",
    motion: "hinge",
    description:
      "Balístico de quadril com kettlebell, para potência da cadeia posterior.",
    steps: [
      "Segure o kettlebell com as duas mãos, pés um pouco além da largura dos quadris.",
      "Lance o peso para trás entre as pernas e estenda o quadril com força.",
      "Deixe os braços levarem o kettlebell até a linha do peito, sem levantar com os ombros.",
    ],
    commonMistake: "Agachar em vez de dobrar o quadril, ou elevar o peso com os braços.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 53,
    videoId: "YSxHifyI6s8",
    videoSource: "Men's Health",
    videoUrl: "https://www.youtube.com/watch?v=YSxHifyI6s8",
    equipmentRequired: ["kettlebell"],
    locationCompatible: HOME_LOCATIONS,
    equipmentAlternatives: [
      { missing: "kettlebell", substituteExerciseId: "dumbbell-rdl" },
      { missing: "kettlebell", substituteExerciseId: "glute-bridge" },
    ],
  },
  {
    id: "side-plank",
    name: "Prancha lateral",
    muscleGroup: "Abdômen",
    secondaryMuscles: ["Ombros", "Glúteos"],
    equipment: "Peso corporal",
    difficulty: "Intermediário",
    motion: "plank",
    description:
      "Isometria de lado para oblíquos e estabilidade do tronco.",
    steps: [
      "Apoie o antebraço no chão, cotovelo sob o ombro, corpo de lado.",
      "Eleve o quadril até formar uma linha da cabeça aos pés.",
      "Segure sem deixar o quadril cair e troque o lado.",
    ],
    commonMistake: "Deixar o quadril afundar ou o ombro escapar para a frente.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Frontal ou lateral",
    sortOrder: 54,
    videoId: "XeN4pEZZJNI",
    videoSource: "Well+Good",
    videoUrl: "https://www.youtube.com/watch?v=XeN4pEZZJNI",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
  },
  {
    id: "bird-dog",
    name: "Bird dog",
    muscleGroup: "Abdômen",
    secondaryMuscles: ["Costas", "Glúteos"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "stability",
    description:
      "Extensão cruzada a quatro apoios para estabilidade do tronco e da lombar.",
    steps: [
      "Fique de quatro com a coluna neutra e o olhar no chão.",
      "Estenda o braço e a perna opostos sem girar o quadril.",
      "Volte com controle e alterne os lados.",
    ],
    commonMistake: "Elevar demais a perna e arquear a lombar.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 55,
    videoId: "CN2VqkSZhFc",
    videoSource: "Jayd Harrison",
    videoUrl: "https://www.youtube.com/watch?v=CN2VqkSZhFc",
    equipmentRequired: ["nenhum"],
    locationCompatible: HOME_LOCATIONS,
  },
  {
    id: "bicycle-crunch",
    name: "Abdominal bicicleta",
    muscleGroup: "Abdômen",
    secondaryMuscles: ["Quadríceps"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "crunch",
    description:
      "Crunch cruzado em movimento, para reto abdominal e oblíquos.",
    steps: [
      "Deite com as mãos leves atrás da cabeça e as pernas elevadas.",
      "Leve o cotovelo em direção ao joelho oposto, estendendo a outra perna.",
      "Alterne os lados sem puxar o pescoço com as mãos.",
    ],
    commonMistake: "Puxar a cabeça com as mãos ou fazer o movimento rápido demais.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 56,
    videoId: "9FGilxCbdz8",
    videoSource: "LIVESTRONG",
    videoUrl: "https://www.youtube.com/watch?v=9FGilxCbdz8",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
  },
  {
    id: "lying-leg-raise",
    name: "Elevação de pernas",
    muscleGroup: "Abdômen",
    secondaryMuscles: ["Quadríceps"],
    equipment: "Peso corporal",
    difficulty: "Intermediário",
    motion: "raise",
    description:
      "Elevação de pernas deitado, para a porção inferior do abdômen com controle da lombar.",
    steps: [
      "Deite com as pernas estendidas e as mãos ao lado do corpo ou sob o quadril.",
      "Eleve as pernas até perto da vertical, sem balançar.",
      "Desça com controle até quase tocar o chão, mantendo a lombar apoiada.",
    ],
    commonMistake: "Arquear a lombar no fundo ou usar impulso para subir.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 57,
    videoId: "JB2oyawG9KI",
    videoSource: "LIVESTRONG",
    videoUrl: "https://www.youtube.com/watch?v=JB2oyawG9KI",
    equipmentRequired: ["nenhum"],
    locationCompatible: HOME_LOCATIONS,
  },
  {
    id: "mountain-climber",
    name: "Escalador",
    muscleGroup: "Abdômen",
    secondaryMuscles: ["Quadríceps", "Ombros"],
    equipment: "Peso corporal",
    difficulty: "Iniciante",
    motion: "cardio",
    description:
      "Corrida em prancha para abdômen, ombros e ritmo, sem equipamento.",
    steps: [
      "Comece em prancha alta, pulsos sob os ombros e corpo em linha.",
      "Leve um joelho em direção ao peito e troque as pernas em ritmo constante.",
      "Mantenha o quadril baixo e o olhar no chão à frente das mãos.",
    ],
    commonMistake: "Elevar o quadril ou deixar os ombros caírem para a frente das mãos.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 58,
    videoId: "DyeZM-_VnRc",
    videoSource: "LIVESTRONG",
    videoUrl: "https://www.youtube.com/watch?v=DyeZM-_VnRc",
    equipmentRequired: ["nenhum"],
    locationCompatible: ALL_LOCATIONS,
  },
  {
    id: "seated-calf-raise",
    name: "Panturrilha sentada",
    muscleGroup: "Panturrilhas",
    secondaryMuscles: ["Quadríceps"],
    equipment: "Máquina",
    difficulty: "Iniciante",
    motion: "raise",
    description:
      "Elevação de calcanhares sentado, para o sóleo, complementar à panturrilha em pé.",
    steps: [
      "Sente com a ponta dos pés no apoio e os joelhos sob a almofada ou a carga.",
      "Desça os calcanhares até alongar a panturrilha.",
      "Suba na ponta dos pés e segure um instante no topo.",
    ],
    commonMistake: "Usar impulso dos joelhos ou encurtar a descida.",
    analyzable: false,
    analysisProfile: null,
    cameraView: "Lateral",
    sortOrder: 59,
    videoId: "ORY-ke6vcgk",
    videoSource: "Runna",
    videoUrl: "https://www.youtube.com/watch?v=ORY-ke6vcgk",
    equipmentRequired: ["maquinas"],
    locationCompatible: GYM_ONLY,
    equipmentAlternatives: [
      { missing: "maquinas", substituteExerciseId: "standing-calf-raise" },
    ],
  },
];

type CatalogSeed = Omit<
  Exercise,
  "equipmentRequired" | "locationCompatible" | "equipmentAlternatives"
> &
  Partial<
    Pick<
      Exercise,
      "equipmentRequired" | "locationCompatible" | "equipmentAlternatives"
    >
  >;

export type { CatalogSeed };

export function applyCatalogGear(exercises: CatalogSeed[]): Exercise[] {
  return exercises.map((exercise) => {
    const gear = CATALOG_GEAR[exercise.id];
    return {
      ...exercise,
      equipmentRequired:
        exercise.equipmentRequired ?? gear?.equipmentRequired ?? ["nenhum"],
      locationCompatible:
        exercise.locationCompatible ??
        gear?.locationCompatible ??
        ALL_LOCATIONS,
      equipmentAlternatives:
        exercise.equipmentAlternatives ?? gear?.equipmentAlternatives,
    };
  });
}
