/**
 * Grafo explícito de substituição. A ordem em cada lista é a prioridade.
 * O motor só oferece o que passa no filtro de equipamento, nível e músculo.
 */
export const SUBSTITUTION_GRAPH: Record<string, string[]> = {
  "push-up": [
    "incline-push-up",
    "knee-push-up",
    "floor-dumbbell-press",
    "decline-push-up",
    "dumbbell-fly",
  ],
  "incline-push-up": ["push-up", "knee-push-up"],
  "knee-push-up": ["incline-push-up", "push-up"],
  "decline-push-up": ["push-up", "incline-push-up", "floor-dumbbell-press"],
  "dumbbell-fly": ["floor-dumbbell-press", "incline-dumbbell-press", "push-up"],
  "bench-press": [
    "incline-dumbbell-press",
    "floor-dumbbell-press",
    "dumbbell-fly",
    "push-up",
  ],
  "incline-dumbbell-press": ["floor-dumbbell-press", "dumbbell-fly", "push-up"],
  "floor-dumbbell-press": ["push-up", "incline-dumbbell-press"],
  "pull-up": [
    "chin-up",
    "lat-pulldown",
    "inverted-row",
    "dumbbell-row",
    "superman",
  ],
  "chin-up": ["pull-up", "lat-pulldown", "inverted-row"],
  "barbell-row": ["dumbbell-row", "seated-cable-row", "inverted-row", "superman"],
  "lat-pulldown": ["pull-up", "chin-up", "inverted-row", "superman"],
  "seated-cable-row": ["dumbbell-row", "inverted-row", "barbell-row"],
  "inverted-row": ["dumbbell-row", "seated-cable-row", "superman", "barbell-row"],
  "dumbbell-row": ["inverted-row", "seated-cable-row", "barbell-row", "superman"],
  superman: ["inverted-row", "dead-bug"],
  "shoulder-press": ["arnold-press", "pike-push-up", "front-raise", "lateral-raise"],
  "arnold-press": ["shoulder-press", "pike-push-up", "front-raise"],
  "lateral-raise": ["front-raise", "reverse-fly", "shoulder-press", "pike-push-up"],
  "front-raise": ["lateral-raise", "shoulder-press", "pike-push-up"],
  "reverse-fly": ["band-pull-apart", "face-pull", "lateral-raise"],
  "band-pull-apart": ["reverse-fly", "face-pull", "superman"],
  "pike-push-up": ["shoulder-press", "push-up"],
  shrug: ["reverse-fly", "band-pull-apart"],
  "face-pull": ["band-pull-apart", "reverse-fly", "superman", "inverted-row"],
  "barbell-curl": ["hammer-curl", "concentration-curl", "towel-curl"],
  "hammer-curl": ["concentration-curl", "barbell-curl", "towel-curl"],
  "concentration-curl": ["hammer-curl", "barbell-curl", "towel-curl"],
  "towel-curl": ["hammer-curl", "inverted-row"],
  "bench-dip": [
    "diamond-push-up",
    "dumbbell-tricep-extension",
    "tricep-kickback",
    "triceps-pushdown",
  ],
  "triceps-pushdown": [
    "dumbbell-tricep-extension",
    "overhead-tricep-extension",
    "diamond-push-up",
    "bench-dip",
  ],
  "diamond-push-up": ["bench-dip", "push-up", "dumbbell-tricep-extension"],
  "dumbbell-tricep-extension": [
    "overhead-tricep-extension",
    "tricep-kickback",
    "diamond-push-up",
    "triceps-pushdown",
  ],
  "tricep-kickback": [
    "dumbbell-tricep-extension",
    "diamond-push-up",
    "triceps-pushdown",
  ],
  "overhead-tricep-extension": [
    "dumbbell-tricep-extension",
    "diamond-push-up",
    "triceps-pushdown",
  ],
  "bodyweight-squat": [
    "goblet-squat",
    "wall-sit",
    "reverse-lunge",
    "leg-press",
  ],
  "goblet-squat": ["bodyweight-squat", "wall-sit", "reverse-lunge"],
  "wall-sit": ["bodyweight-squat", "goblet-squat"],
  "reverse-lunge": [
    "bulgarian-split-squat",
    "step-up",
    "bodyweight-squat",
    "goblet-squat",
  ],
  "bulgarian-split-squat": ["reverse-lunge", "step-up", "goblet-squat"],
  "step-up": ["reverse-lunge", "bulgarian-split-squat", "bodyweight-squat"],
  "leg-press": ["goblet-squat", "bodyweight-squat"],
  "romanian-deadlift": [
    "dumbbell-rdl",
    "kettlebell-swing",
    "glute-bridge",
    "single-leg-glute-bridge",
  ],
  "dumbbell-rdl": ["romanian-deadlift", "glute-bridge", "kettlebell-swing"],
  "kettlebell-swing": ["dumbbell-rdl", "glute-bridge", "romanian-deadlift"],
  "hip-thrust": ["glute-bridge", "single-leg-glute-bridge", "donkey-kick"],
  "glute-bridge": ["single-leg-glute-bridge", "donkey-kick", "hip-thrust"],
  "single-leg-glute-bridge": ["glute-bridge", "donkey-kick", "hip-thrust"],
  "donkey-kick": ["glute-bridge", "single-leg-glute-bridge"],
  plank: ["side-plank", "bird-dog", "dead-bug", "crunch"],
  "side-plank": ["plank", "bird-dog", "dead-bug"],
  "bird-dog": ["dead-bug", "plank", "side-plank"],
  "dead-bug": ["bird-dog", "plank", "crunch"],
  crunch: ["bicycle-crunch", "lying-leg-raise", "plank", "dead-bug"],
  "bicycle-crunch": ["crunch", "lying-leg-raise", "mountain-climber"],
  "lying-leg-raise": ["bicycle-crunch", "crunch", "plank"],
  "mountain-climber": ["plank", "bicycle-crunch", "dead-bug"],
  "standing-calf-raise": ["seated-calf-raise"],
  "seated-calf-raise": ["standing-calf-raise"],
};

export function graphAlternatives(exerciseId: string): string[] {
  return SUBSTITUTION_GRAPH[exerciseId] ?? [];
}
